---
# handlers file for pi_audio_apps
handlers:
  - name: restart_squeezelite
    become: true
    service:
      name: squeezelite
      state: restarted

  - name: restart_raspotify
    become: true
    service:
      name: raspotify
      state: restarted
