---
- name: audio config
  hosts: "{{ host | default('none') }}"
  gather_facts: True


  tasks:
  - name: setup hifiberry cards
    block:

      - name: set the available hifi berry cards
        set_fact:
          hifiBerryCards:
            - 'hifiberry-dac'
            - 'hifiberry-dacplus'
            - 'hifiberry-digit'
            - 'hifiberry-amp'

      - name: list sound cards
        command: aplay -l
        register: aplayOut

      - debug:
          msg: "found a hifiberry card"
        when:  '"hifiberry" in aplayOut.stdout'

      - set_fact:
          filtered: "{{ aplayOut.stdout | regex_search(hifiBerryCard, '\\3') }}"
        vars:
          hifiBerryCard: "card\\W+(\\d)\\W+(\\w+hifi\\w+)\\W+\\[(.*)\\].*device\\W+(\\d):\\W+(.*)\\[(.*)\\]"

      - name: install soundcard
        pause:
          prompt: "found {{ filtered }} sound card. Would you like to install? (yes/no)"
        register: installSnd

      - name: choose card
        pause:
          prompt: "enter: {{ hifiBerryCards }}"
        register: cardType
        when: installSnd.user_input| bool


      - debug:
          msg: "unknown card type: {{ cardType.user_input }}"
        when: cardType.user_input not in hifiBerryCards

      - name: disable onboard audio
        replace:
          path: /boot/config.txt
          regexp: '^(dtparam=audio=on)'
          replace: '#\1'
        become: true
        notify: reboot
        when: cardType.user_input in hifiBerryCards
#        debug:
#          msg: 'commented out dtparm=audio=on line'

      - name: force_eeprom_read for linux 5.4 and higher
        lineinfile:
          path: /boot/config.txt
          regexp: ^force_eeprom_read=
          line: force_eeprom_read=0
        become: true
        notify: reboot
        when: cardType.user_input in hifiBerryCards


      - name: enable hifiberry audio
        lineinfile:
          path: /boot/config.txt
          regexp: ^dtoverlay=
          line: dtoverlay={{ cardType.user_input }}
        # need to add a line for disabling eeprom if kernel is 5.4
        # force_eeprom_read=0
        become: true
        notify: reboot
        when: cardType.user_input in hifiBerryCards

      - name: configure ALSA
        copy:
          src: "./files/asound.conf"
          dest: /etc/asound.conf
          owner: root
          group: root
          mode: 0644
        become: true
        notify: reboot
        when: cardType.user_input in hifiBerryCards
 
  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      become: true


# add a handler for reboot here
