---
- name: setup spi interface 
  hosts: "{{ host | default('none') }}"
  gather_facts: no

  tasks:
  
  - name: set spi on in config.txt
    lineinfile:
      path: /boot/config.txt
      regexp: (?:#)?dtparam=spi=.*
      line: dtparam=spi=on
    become: true
    notify: reboot

  - name: set black list
    set_fact:
      blacklist: /etc/modprobe.d/raspi-blacklist.conf

  - name: touch blacklist
    file:
      path: "{{ blacklist }}"
      state: touch
      mode: '1644'
    become: true


  - name: remove bcm2780 from blacklist
    replace:
      path: /etc/modprobe.d/raspi-blacklist.conf
      regexp: '(^blacklist\s{0,}spi[_-]bcm2708)'
      replace: '#\1'
    become: true
    notify: reboot

  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 45
        test_command: whoami
      become: true
    
