---
- name:  config
  hosts: "{{ host | default('none') }}"
  gather_facts: yes
  vars:
    spocon_config: "/opt/spocon/config.toml"

  tasks:
    - name: gather installed debian packages
      package_facts:
        manager: "auto"

    - name: install and configure squeezelite
      block:

      - name: install necessary packages
        apt:
          pkg:
          - curl
          - apt-transport-https
          - squeezelite
          state: latest
        become: true
        when: "'squeezelite' not in ansible_facts.packages"

      - name: set sound output device
        lineinfile:
          path: /etc/default/squeezelite
          regexp: '^SL_SOUNDCARD="\w+"'
          line: 'SL_SOUNDCARD="sysdefault:CARD=sndrpihifiberry"'
          state: present
          backup: yes
        become: true
        register: match
        notify: restart_squeezelite

      - name: set squeezelite timeout for soundcard release
        lineinfile:
          path: /etc/default/squeezelite
          regexp: '^SB_EXTRA_ARGS="-C \d+"'
          line: 'SB_EXTRA_ARGS="-C 10"'
          state: present
          backup: yes
        become: true
        register: match
        notify: restart_squeezelite




    - name: install spocon
      block:
        - name: get spocon installer script
          get_url:
            url: https://spocon.github.io/spocon/install.sh 
            dest: /tmp/spocon-installer.sh
            mode: 0755

        - name: execute spocon installer script
          shell: /tmp/spocon-installer.sh

        - name: cleanup spocon script
          file:
            path: /tmp/spocon-installer.sh
            state: absent
      become: true
      when: "'spocon' not in ansible_facts.packages"


    - name: configure spocon for paperpi
      block:

        - name: prompt spocon name
          pause:
            prompt: 'what name should be usded for this spocon instance? Suggested: Spotify-{{ansible_hostname}}'
          register: spocon_name
          until:
            - spocon_name.user_input|length > 0
          retries: 4
          delay: 1

        - name: set initial volume to 1/2 of max (65536)
          ansible.builtin.lineinfile:
            backup: yes
            backrefs: yes
            state: present
            path: "{{spocon_config}}"
            regexp: '^(\s+)?initialVolume.*'
            line: '\1initialVolume = 32768'
          notify: restart_spocon

        - name: set player name
          ansible.builtin.lineinfile:
            backup: yes
            backrefs: yes
            state: present
            path: "{{spocon_config}}"
            regexp: '^(\s+)?deviceName.*'
            line: '\1deviceName = "{{ spocon_name.user_input}}"'
          notify: restart_spocon

        - name: set device type to Speaker
          ansible.builtin.lineinfile:
            backup: yes
            backrefs: yes
            state: present
            path: "{{spocon_config}}"
            regexp: '^(\s+)?deviceType.*'
            line: '\1deviceType = "SPEAKER"'
          notify: restart_spocon        

        - name: set volume steps
          ansible.builtin.lineinfile:
            backup: yes
            backrefs: yes
            state: present
            path: "{{spocon_config}}"
            regexp: '^(\s+)?volumeSteps.*'
            line: '\1volumeSteps = 100'
          notify: restart_spocon

      become: true





  handlers:
    - name: restart_squeezelite
      become: true
      service:
        name: squeezelite
        state: restarted

    - name: restart_spocon
      become: true
      service:
        name: spocon
        state: restarted  

