---
- name: check hifiberry cards 
  hosts: "{{ host | default('none') }}"
  gather_facts: no

  tasks:

  - name: check card is installed
    block:
      - name: get aplay output
        command: aplay -l
        register: result

      - set_fact:
          aplayOut: "{{ result.stdout }}"

      - set_fact:
          filtered: "{{ aplayOut | regex_search(card, '\\1') }}"
        vars:
          card: "card.*rpihifiberry.*\\[.*\\],.*device.*:\\W+(.*)\\[.*"

      - debug:
          msg: "Card successfully installed: {{ filtered }}"
        when: filtered|length > 0

      - debug:
          msg: "FAILED to install hifi berry card-- aplay output: {{ aplayOut }}"
        when: filtered| length < 1


  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 45
        test_command: whoami
      become: true
    
