---
- name: enable shutdown button on GPIO3 (pins 5, 6)
  hosts: "{{ host | default('none') }}"
  gather_facts: no

  tasks:
    - name: add shutdown line to config.txt
      lineinfile:
        state: present
        regexp: '^dtoverlay=gpio-shutdown.*'
        line: 'dtoverlay=gpio-shutdown,gpio_pin=17,active_low=1'
        path: /boot/config.txt
      become: true
      notify: reboot

    - name: setup shutdown button
      pause:
        prompt: "Add a button to pins 6 (Gnd) and 11 (GPIO-17) to enable shutdowns; optionally add a button to pins 6 (Gnd) and 5 (GPIO-3) to wake from shutdown."

  handlers:
    - name: reboot
      reboot:
        msg: "reboot initated by ansible"
        pre_reboot_delay: 0
      become: true
