---
- name: install led control script and unit file
  hosts: "{{ host | default('none') }}"
  gather_facts: no

  tasks:
  - name: activity trigger none
    lineinfile:
      path: /boot/config.txt
      regexp: dtparam=act_led_trigger=.*
      line: dtparam=act_led_trigger=none
    become: true

  - name: activity led active low
    lineinfile:
      path: /boot/config.txt
      regexp: dtparam=act_led_activelow=.*
      line: dtparam=act_led_trigger=on
    become: true

  - name: pwr led trigger none
    lineinfile:
      path: /boot/config.txt
      regexp: dtparam=pwr_led_trigger=.*
      line: dtparam=pwr_led_trigger=none
    become: true

  - name: pwr led trigger acive low off
    lineinfile:
      path: /boot/config.txt
      regexp: dtparam=pwr_led_activelow=.*
      line: dtparam=pwr_led_acitvelow=off
    become: true

  - name: copy light control script
    copy:
      src: ./files/led_ctl
      dest: /usr/bin
      mode: '0764'
    become: true

  - name: copy unit file for led control
    copy:
      src: ./led_ctl.service
      dest: /etc/systemd/system
    become: true

  - name: enable led control unit file
    systemd:
      enabled: yes
      name: led_ctl.service
    become: true

  - name: switch off leds
    systemd:
      state: started
      name: led_ctl.service
    become: true



  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 45
        test_command: whoami
      become: true
    
