---
- name: setup i2c interface 
  hosts: "{{ host | default('none') }}"
  gather_facts: no

  tasks:
  - name: set i2c on in config.txt
    lineinfile:
      path: /boot/config.txt
      regexp: (^#\s{0,}dtparam=i2c_arm=.*)|(^dtparam=i2c_arm=.*)
      line: dtparam=i2c_arm=on
    become: true

  - name: remove bcm2780 from blacklist
    replace:
      path: /etc/modprobe.d/raspi-blacklist.conf
      regexp: '(^blacklist\s{0,}i2c[_-]bcm2708)'
      replace: '#\1'
    become: true

  - name: add the i2c-dev module to /etc/modules
    lineinfile:
      path: /etc/modules
      state: present
      line: i2c-dev
  
  - name: add dtparam overlay for i2c
    shell:
      cmd: dtparam i2c_arm=on
    become: true

  - name: probe kernel modules
    modprobe:
      name: i2c-dev
      state: present

    become: true



  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 45
        test_command: whoami
      become: true
    
