---
- name: spocon installer
  hosts: "{{ host | default('none') }}"
  gather_facts: yes
  vars:
    spocon_config: /opt/spocon/config.toml



  tasks:
  - name: add spocon ppa key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7DBE8BF06EA39B78
      state: present
    become: true

  - name: add ppa repo
    apt_repository:
      repo: deb http://ppa.launchpad.net/spocon/spocon/ubuntu bionic main
      state: present
    become: true

  - name: update cache
    apt:
      update_cache: yes
      cache_valid_time: 86400
    become: true


  - name: install spocon
    apt:
      pkg:
        - spocon
    become: true



  - name: spocon config - deviceType
    lineinfile:
      path: "{{ spocon_config }}"
      regexp: '^deviceType.*'
      line: deviceType = "SPEAKER"
    become: true

  - name: spocon config - deviceName
    lineinfile:
      path: "{{ spocon_config }}"
      regexp: '^deviceName.*'
      line: 'deviceName = "{{ ansible_hostname }}-SpoCon"'
    become: true

  - name: spocon config - initialVolume
    replace:
      dest: "{{ spocon_config }}"
      regexp: '(.*)initialVolume.*'
      replace: '\1initialVolume = 39321'
    become: true

  - name: spocon config - releaseLineDelay
    replace:
      dest: "{{ spocon_config }}"
      regexp: '(.*)releaseLineDelay.*'
      replace: '\1releaseLineDelay = 10'
    become: true


  - name: restart spocon service
    systemd:
      state: restarted
      daemon_reload: yes
      name: spocon
    become: true

