---
- name: install basics
  hosts: "{{ host | default('none') }}"
  gather_facts: yes

  tasks:
    - name: set /etc/locale.gen
      shell: 'perl -pi -e "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen'
      become: true

    - name: generate and update locale
      shell: 'locale-gen en_US.UTF-8; update-locale en_US.UTF-8'
      become: true

    - name: update cache
      register: updatesys
      apt:
        update_cache: yes
        cache_valid_time: 86400 # one day
      become: true

    - name: upgrade packages
      register: updatesys
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 86400
      become: true

    - name: Display previous task to check stats
      debug:
        msg: "{{ updatesys.stdout_lines|last }}"

    - name: install packages
      apt:
        pkg:
          - tmux
          - vim
          - git
          - lnav
          - python3
          - python3-setuptools
          - python3-pip
          - python3-full
          - zsh
        state: latest
      become: true

    # - name: remove EXTERNALLY-MANAGED
    #   file:
    #     path: "/usr/lib/python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED"
    #     state: absent
    #   become: true
  
    - name: install python packages
      pip:
        executable: pip3
        extra_args: --user --break-system-packages
        name:
          - dotfiles

    - name: create .ssh directory
      file:
        path: ~/.ssh
        state: directory

    - name: add authorized key
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Setting keypairs
      openssh_keypair:
        path: ~/.ssh/id_rsa
      register: ssh_output

    - pause:
        prompt: "Title: [{{ ansible_date_time.date }}] {{ host }}\n\n{{ ssh_output.public_key }}\n\nregister the public key above with github at the following address and then press enter:\nhttps://github.com/txoof/Dotfiles/settings/keys/new"


    - name: scan and register keys from host -- github
      command: "ssh-keyscan github.com"
      register: host_keys
      changed_when: false

#    - debug:
#        msg: "{{ host_keys.stdout_lines[0] }}"

    - name: add keys for remote host -- github
      known_hosts:
        name: "github.com" 
        state: present
        key: "{{ host_keys.stdout_lines[0] }}"

    - name: add stored keys from github
      authorized_key:
        user: pi
        state: present
        key: https://github.com/txoof.keys

    - name: clone dotfiles repo
      git:
        repo: "git@github.com:txoof/Dotfiles.git"
        dest: "~/Dotfiles"
        clone: yes
        update: yes

    - name: clone development tools
      git:
        repo: git@github.com:txoof/develtools.git
        dest: ~/bin/develtools
        clone: yes
        update: yes

    - name: set shell to zsh
      user:
        name: pi
        shell: /usr/bin/zsh
      become: yes

    - name: clone oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: ~/.oh-my-zsh


    - name: set symlink for dotfilesrc
      file:
        src: ~/Dotfiles/dotfilesrc
        dest: ~/.dotfilesrc
        state: link

    - name: link dotfiles
      command: /home/pi/.local/bin/dotfiles -s --force
