---
- name: NONE 
  hosts: "{{ host | default('none') }}"
  gather_facts: yes

  tasks:
  - name: add key for raspotify repo
    apt_key:
      url: https://dtcooper.github.io/raspotify/key.asc
      state: present
    become: true

  - name: add apt repo for raspotify
    apt_repository:
      repo: deb https://dtcooper.github.io/raspotify raspotify main
      state: present
    become: true

  - name: install rapotify package
    apt:
      update_cache: yes
      pkg: raspotify
      state: latest
    become: true

  - name: set volume args
    lineinfile:
      path: /etc/default/raspotify
      regexp: "^VOLUME_ARGS=.*"
      line: VOLUME_ARGS="--enable-volume-normalisation --initial-volume=50"
    notify: restart_raspotify
    become: true

  - name: set raspotify name
    lineinfile:
      path: /etc/default/raspotify
      regexp: ^DEVICE_NAME=.*
      line: DEVICE_NAME="{{ ansible_nodename }}"
    notify: restart_raspotify
    become: true



  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 45
        test_command: whoami
      become: true

    - name: restart_raspotify
      become: true
      service:
        name: raspotify
        state: restarted
    
