---
- name: development environment basics
  hosts: "{{ host | default('none') }}"
  gather_facts: yes

  tasks:
    - name: update cache
      register: updatesys
      apt:
        update_cache: yes
        cache_valid_time: 86400 # one day
      become: true

    - name: upgrade packages
      register: updatesys
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 86400
      become: true

    - name: Display previous task to check stats
      debug:
        msg: "{{ updatesys.stdout_lines|last }}"

    - name: install packages
      apt:
        pkg:
          - tmux
          - vim
          - git
          - python3
          - python3-setuptools
          - python3-pip
          - zsh
          - python3-gpiozero
          - python3-dev
          - virtualenv
          - curl
        state: latest
      become: true
       
    - name: make home bin directory 
      file:
        path: ~/bin/
        state: directory

    - name: clone development scripts from github
      git:
        repo: "git@github.com:txoof/develtools.git"
        dest: "~/bin/develtools"
        clone: yes
        update: yes
      ignore_errors: yes

    - name: Get Python version
      command: python3 -c "import sys; print('.'.join(map(str, sys.version_info[:2])))"
      register: py_version
      changed_when: False

    - name: Create a virtual environment
      command: 
        cmd: python3 -m venv ~/venv-python-{{ py_version.stdout}}
    
    - name: Install python packages using virtual environment
      pip:
        name: 
          - jupyter
          - jupyter_contrib_nbextensions
          - jupytext
        virtualenv: ~/venv-python-{{ py_version.stdout}}