---
- name: Disable Passwd Login
  hosts: "{{ host | default('none') }}"
  gather_facts: no

  tasks:
  - name: sshd-- ChallengeResponseAuthentication no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^ChallengeResponseAuthentication'
      line: ChallengeResponseAuthentication no
      create: yes
      state: present
    become: true

  - name: sshd-- PasswordAuthentication no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: PasswordAuthentication no
      create: yes
      state: present
    become: true

  - name: sshd-- UsePAM no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^UsePAM'
      line: UsePam no
      create: yes
      state: present
    become: true

  - name: sshd-- PermitRootLogin no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: PermitRootLogin no
      create: yes
      state: present
    become: true


  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 45
        test_command: whoami
      become: true
    
