---
- name: NONE 
  hosts: "{{ host | default('none') }}"
  gather_facts: no

  tasks:
  - debug:
      msg: "this sis\nmulti line\text"


  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 45
        test_command: whoami
      become: true
    
